#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Check commit msg spelling:${no_color}"
FORCE_COLOR=1 yarn -s cspell --show-suggestions --relative --no-summary $1
echo -e "\n${yellow}Check conventional commit msg:${no_color}"
npx commitlint --edit $1
